### PR TITLE
Changed references from .zshrc to .bashrc

### PR DESCRIPTION
**Pull request by jordan-castelloe**
NewForce students are all using Windows laptops provided by Mountwest, so we don't have any Mac users. Everyone's using git bash, so I changed references to the `.zshrc` file to `.bashrc` file and added instructions for creating a `.bashrc` file in the root directory.

### CODE REVIEW

**Review by kimpreece — COMMENTED** [review]
Looks good!   Is there sudo on git bash for windows? line 21 & 26

I need to work on my function on the exercise - it's not working.

**Comment by jordan-castelloe** [comment]
Just kidding @kimpreece! New intel. I think we should be adding aliases and whatnot to .bash_profile instead of .bashrc. Either one will work, but I'm pretty sure this is the most direct way to do it. I changed it again... sorry

**Comment by jordan-castelloe** [comment]
And no, I don't think there's sudo for windows. I reckon we should take that out too, or leave it in in case anybody has macs at home?

**Review by kimpreece — COMMENTED** [review]
awesome.   a couple of files were created when i restarted git bash after I added the .bashrc file including .bash_profile

**Pull request closed without merging**
